import type { Metadata } from "next";
import { Tenor_Sans, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header/Header";
import Footer from "@/component/Footer/Footer";
import { ModalProvider } from "@/app/context/ModalProvider";



const nunitoSans = Nunito({
  weight: ["300", "400", "500"],
  variable: "--font-nunito",
  subsets: ["latin", "cyrillic"],
});

const tenorSans = Tenor_Sans({
  weight: "400",
  variable: "--font-tenor-sans",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${tenorSans.className} ${nunitoSans.className} antialiased`}>
        <ModalProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
